version: '3'
services:
 node:
   build: .
   tty: true
   container_name: node
   expose:
     - "8080"
   #ports:
   #  - "8080:8080"
   volumes:
     - './:/usr/src'
   working_dir: '/usr/src'

 nginx:
   build: ./nginx
   tty: true
   container_name: nginx
   ports:
     - "80:8000"
   volumes:
     - "./media:/usr/local/media"
     - "./blog/static:/usr/local/static"
     - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
   depends_on:
     - node
