version: '3'
services:
 node:
   build: ./docker/node
   tty: true
   container_name: node
   expose:
     - "8080"
   volumes:
     - './:/usr/src'
   working_dir: '/usr/src'

 nginx:
   build: ./docker/nginx
   tty: true
   container_name: nginx
   ports:
     - "80:8000"
   volumes:
     - "./media:/usr/local/media"
     - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
   depends_on:
     - node

 memcached:
   build: ./docker/memcached
   tty: true
   container_name: memcached
   ports:
     - "11211:11211"
